language: ruby
rbenv:
- 2.6.4
before_install:
- nvm install 10
addons:
  postgresql: 9.6
script:
- unset DATABASE_URL
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  app:
  run: rails db:migrate