os: osx
language: ruby
rbenv:
- 2.6.4
before_install:
- nvm install 10
before_script:
- sudo systemsetup -settimezone America/Los_Angeles
addons:
  postgresql: 9.6
script:
- unset DATABASE_URL
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: OHBK5Ke+x/yaFLkTibyfJEItF73d6BKQwhzYqg3MBjeacwShpnvEMdtVLwPfV0maYCeFNlcUbSsIqEz5D9WFNeoQQBXfmnwqO1avqCclEyCrhUF9dEEdQoqE04mx32clslSe45VS31hMdHcYUi7BsxV2AQE0CkJsnWwUWnitBMo4+8BphVaVt4wg34yugpj/SLzbn/rLEZxLE/2+IhQtBzHkxwn7UwoVSbuzL/4YExBXUPE02yLZKE5n7TnY6mV5i9eMbvGkT8R1uM03swt90MrVwwzieuxXnV7tpfN42mzqKGpdwVW9d4riwmVqqPsJo/vzpvr+dLrHb7X/FcfLVddxXaQ6RCE4IZpqwJrGZNBR9ZqCV14eSVt0wDCq534+02nCrVrtwo3HC9yuHa3afcAPGAITVhixhDjgeCx/n7sM1xUlpnFSHf2qm29qhRiydINdKmqHyNFaXxBNr2oCFQ1Y0JPOUXebGejUhjJNFSLvHq2nWQEB5uzYfh9/KLSClpCgmkLmmvKeVrBRX2SOYOQVvsMmrW7FS2qFO+eUt6+S/9ha51ikZ4ujnp4YTaZ5t2Cm6JhMYD+hgIpulZ6TsiDxvmJd+ZJxL2qlvnaDLWuGOW2Dd51HdrGhHlZkNTdMYzlvRbdM4rXiJRLQ4bdOEvjd8dr51nk6WFmf7gRvPVI=
  app: austin-weather-charts
  run: rails db:migrate
